# Generated by Django 3.2.8 on 2021-10-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='sectiontree',
            name='level',
        ),
        migrations.RemoveField(
            model_name='sectiontree',
            name='parent',
        ),
        migrations.AddField(
            model_name='sectiontree',
            name='Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.section'),
        ),
    ]
