# Generated by Django 3.2.8 on 2021-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211022_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='TreeSum',
            field=models.CharField(default=1, max_length=200, verbose_name='TreeSum'),
        ),
    ]
