# Generated by Django 3.2.8 on 2021-10-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_section_treesum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='TreeSum',
            field=models.IntegerField(default=0, max_length=200, verbose_name='TreeSum'),
        ),
    ]
