# Generated by Django 3.2.8 on 2021-10-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_section_treesum'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='describe',
            field=models.CharField(max_length=50, null=True, verbose_name='describe'),
        ),
        migrations.AddField(
            model_name='sectiontree',
            name='describe',
            field=models.CharField(max_length=50, null=True, verbose_name='describe'),
        ),
    ]
