# Generated by Django 3.2.8 on 2021-10-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_section_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='sectiontree',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='照片'),
        ),
    ]
