# Generated by Django 3.2.8 on 2021-10-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211022_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('section', models.CharField(max_length=255, verbose_name='section')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articlesystem')),
            ],
        ),
    ]
