# Generated by Django 3.2.8 on 2021-10-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articlesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesystem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articlesystem'),
        ),
    ]
