# Generated by Django 3.2.8 on 2021-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articlesystem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesystem',
            name='parent',
            field=models.IntegerField(default=0, max_length=200, verbose_name='parent'),
        ),
    ]
