# Generated by Django 3.2.8 on 2021-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_articlesystem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesystem',
            name='level',
            field=models.IntegerField(default=1, max_length=200, verbose_name='level'),
        ),
    ]
