# Generated by Django 3.2.8 on 2021-10-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_articlesystem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ftitle',
            field=models.CharField(default='null', max_length=255, verbose_name='ftitle'),
        ),
    ]
