# Generated by Django 3.2.8 on 2021-10-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_articlesystem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.IntegerField(default=0, max_length=200, verbose_name='parent'),
        ),
        migrations.DeleteModel(
            name='SectionTree',
        ),
    ]
