# Generated by Django 3.2.8 on 2021-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20211024_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesystem',
            name='section',
            field=models.IntegerField(max_length=200, verbose_name='section'),
        ),
    ]
