# Generated by Django 3.2.8 on 2021-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211024_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='time'),
        ),
    ]
