# Generated by Django 3.2.8 on 2021-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_article_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('body', models.CharField(max_length=255, verbose_name='body')),
                ('writer', models.CharField(max_length=255, verbose_name='writer')),
                ('time', models.DateField(auto_now=True, verbose_name='time')),
            ],
        ),
    ]
