# Generated by Django 3.2.8 on 2021-10-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_timemess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemess',
            name='name',
        ),
    ]
