# Generated by Django 3.2.8 on 2021-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_timemess_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesystem',
            name='level',
        ),
        migrations.AddField(
            model_name='articlesystem',
            name='sum',
            field=models.IntegerField(default=0, max_length=200, verbose_name='sum'),
        ),
    ]
