# Generated by Django 3.2.8 on 2021-10-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20211024_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesystem',
            name='level',
            field=models.IntegerField(default=1, max_length=200, verbose_name='level'),
        ),
    ]
