# Generated by Django 3.2.8 on 2021-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_articlesystem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadimg/', verbose_name='照片'),
        ),
    ]
