# Generated by Django 3.2.8 on 2021-10-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='time'),
        ),
    ]
