# Generated by Django 3.2.8 on 2021-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_remark_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='parent',
            field=models.IntegerField(default=0, max_length=200, verbose_name='parent'),
        ),
    ]
